# Generated by Django 2.2.3 on 2019-11-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantModel',
            fields=[
                ('Merchant_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Merchant_Name', models.CharField(max_length=30)),
                ('Merchant_Contact', models.IntegerField(unique=True)),
                ('Merchant_Email', models.EmailField(max_length=254, unique=True)),
                ('Merchant_Password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NO', models.IntegerField(unique=True)),
                ('PRODUCT_NAME', models.CharField(max_length=30)),
                ('PRODUCT_PRICE', models.FloatField()),
                ('PRODUCT_QUANTITY', models.IntegerField()),
                ('Merchant_Id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.MerchantModel')),
            ],
        ),
    ]
